Executor unit tests
connext/nxtp pull request #1383
Opened 2022-06-08 17:13 UTC by wanglonghong

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2022-06-09 19:18 UTC, LayneHaber commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +
also we should handle this failure gracefully otherwise funds will get parked in the executor

2022-06-09 19:24 UTC, LayneHaber approved these changes

2022-06-09 22:11 UTC, jakekidd commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +   * @dev Contracts that are being called during `execute` may set
nit: Can we move this really great description of "properties" in general to be under the `// ============ Properties =============`

2022-06-09 22:12 UTC, jakekidd commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +   * @dev This is always accessible via reentrancy. May *NOT* be the exact amount
This description feels misleading. This value *should* be accessed via reentrancy, and will be set only for the duration of the execution

2022-06-09 22:13 UTC, jakekidd commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +   * @dev This is always accessible via reentrancy. May *NOT* be the exact amount
Let's move this description to all be under that general "Properties" comment under `// ============ Properties =============`

2022-06-09 22:21 UTC, jakekidd commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +    if (_amount == 0) {
what happens if we got here with `msg.value != _args.amount` ??

If the amount is 0 but the msg.value has some extra (somehow, idk how), then that msg.value will get stuck here.

2022-06-09 22:24 UTC, jakekidd commented on packages/deployments/contracts/contracts_forge/core/connext/helpers/Executor.t.sol
> +  // Should gracefully handle failures if value != amount
On top of the previous comment about the edge case where value != amount, and amount == 0, would like to see that case tested here

2022-06-09 22:25 UTC, jakekidd requested changes
need to handle the edge case I mentioned here

2022-06-09 22:31 UTC, jakekidd approved these changes
my bad, edge case is invalid - we're passing in msg.value as amount. looks good!

2022-06-09 23:50 UTC, LayneHaber commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
>  // import {ExcessivelySafeCall} from "@nomad-xyz/excessively-safe-call/src/ExcessivelySafeCall.sol";
remove what? the nomad import thats commented out?

i don't want to remove it, i would eventually like to use it straight from the package

2022-06-10 01:19 UTC, wanglonghong commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +
Nice!

2022-06-10 08:46 UTC, liu-zhipeng approved these changes

2022-06-10 08:51 UTC, merged