Improving root level readme
connext/nxtp pull request #1470
Opened 2022-07-04 19:41 UTC by duckdegen

Improving readme

2022-07-04 19:42 UTC, duckdegen commented
@rhlsthrm plz provide some feedback. This will be updated more in the near future, but this is just to get a basic update out asap

2022-07-05 03:19 UTC, rhlsthrm requested changes
Really great work here! This is awesome. Just posted a few suggestions to make things more accurate.

2022-07-05 03:19 UTC, rhlsthrm commented on README.md
> +It's architecture can be seen as a layered system, as follows:
```suggestion
The Connext architecture can be seen as a layered system, as follows:
```
"It's" is improper grammar.

2022-07-05 03:19 UTC, rhlsthrm commented on README.md
> +-Prepare a signed transaction object using funds on the receiving chain.
```suggestion
**Routers (Active Liquidity Providers) will:**
-Prepare a signed transaction object using funds on the receiving chain.
```
This is done by routers technically, not contracts.

2022-07-05 03:19 UTC, rhlsthrm commented on README.md
> +Note: if the router does not have enough funds for the transfer, they may also provide only part of the transfer's value.
```suggestion
Note: if the router does not have enough funds for the transfer, they may also provide only part of the transfer's value, which gets split across multiple routers in the network.
```

2022-07-05 03:19 UTC, rhlsthrm commented on README.md
> +-The auctioneer will be observing all of the underlying chains. Every X blocks, the auctioneer will collect bids for transactions. The auctioneer will be responsible for selecting the correct router
```suggestion
-The sequencer collects bids from routers and allows routers 30 seconds per transfer to send bids. After this time, sequencer will select a bid randomly (selection process TBD) and submit the payload which contains the router's signature to the relayer network to be submitted to chain.
```
Modified sequencer algorithm to be more accurate.

2022-07-05 03:19 UTC, rhlsthrm commented on README.md
> +This repo is set up as a yarn workspace monorepo
```suggestion
This repo is set up as a Yarn Workspace monorepo: https://yarnpkg.com/features/workspaces
```

2022-07-07 12:00 UTC, duckdegen commented
updated copy as per comments

2022-07-07 19:27 UTC, rhlsthrm commented
Weird that builds are failing...

2022-07-14 22:45 UTC, merged

2022-07-14 22:45 UTC, rhlsthrm commented
Might be bc of fork. Merged anyways.