Spearbit-45
connext/nxtp pull request #1534
Opened 2022-07-19 18:49 UTC by liu-zhipeng

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2022-07-19 20:40 UTC, jakekidd commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +      SafeERC20.safeApprove(IERC20(_args.assetId), _args.to, 0);
We should only have to reset allowance to 0 if there were "unclaimed" / unspent tokens, right?

If all the tokens were spent, then wouldn't the allowance now be 0?

2022-07-20 00:49 UTC, liu-zhipeng commented on packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol
> +      }
This will decrease allowance as well. so i think we don't need `safeApprove` anymore

2022-07-20 22:11 UTC, LayneHaber requested changes
Personally I don't think we should handle this case. I think it adds two different types of complexity:

(1) It adds more code complexity to the `Executor` contract in general
(2) It breaks the assumption that the only edgecase we handle is around your calldata failing. Calldata that leaves amounts within the `Executor` should be considered improperly implemented `calldata`, and outside of the handling scope of the protocol

I would change my mind if we decided to implement an interface for the `Executor` contract (which if implemented correctly, would remove the need for this handling). For now though, I think we should close this PR and treat this issue as "acknowledged"

2022-07-21 01:03 UTC, liu-zhipeng commented
> Personally I don't think we should handle this case. I think it adds two different types of complexity:
> 
> (1) It adds more code complexity to the `Executor` contract in general (2) It breaks the assumption that the only edgecase we handle is around your calldata failing. Calldata that leaves amounts within the `Executor` should be considered improperly implemented `calldata`, and outside of the handling scope of the protocol
> 
> I would change my mind if we decided to implement an interface for the `Executor` contract (which if implemented correctly, would remove the need for this handling). For now though, I think we should close this PR and treat this issue as "acknowledged"

Agree!

2022-07-21 01:03 UTC, closed without merging