[sdk][router][txService] fee cleanup
connext/nxtp pull request #652
Opened 2021-12-21 13:32 UTC by sanchaymittal

- new: getMainnetEquivalent in utils
- cleanup and fixes in chainreader
- sdk cleanup
- router unit test update
- rmv: gas fee calculation from router
- update operation with new function
- update fee calculation in auction
- update binding
- update: getMainnetEquivalent import for testhook
- update global test hook
- fix unit test
- lint fixes
- cleanup
- new: calculateGasFeeInReceivingTokenForFulfill
- update sdk fulfill
- fix sdk unit test

## The Problem

## The Solution

## Checklist

- [ ] Test manually on `test-ui` using remote chains.
- [ ] Run load tests.
- [ ] Update documentation if needed.
- [ ] Update CHANGELOG.md.

2021-12-22 02:54 UTC, jakekidd commented
ty for this. did not have time to review today but i will circle back tomorrow

2021-12-22 08:27 UTC, wanglonghong requested changes

2021-12-22 08:27 UTC, wanglonghong commented on packages/txservice/src/chainreader.ts
> +    if (chainIdForTokenPrice === 10) {
original chainId is equal to chainIdForGasPrice. so it seems needed to be updated like this
> if (chainIdForGasPrice === 10) {

2021-12-22 08:30 UTC, wanglonghong commented on packages/txservice/src/chainreader.ts
> +    if (chainIdForTokenPrice === 10) {
d5f99bf7fafc475dbd8061670e626d8b786a2dee. fixed in this commit

2021-12-23 13:42 UTC, wanglonghong approved these changes

2021-12-23 13:43 UTC, merged