Polling loop
connext/nxtp pull request #702
Opened 2022-01-05 12:35 UTC by rhlsthrm

## The Problem

## The Solution

## Checklist

- [ ] Test manually on `test-ui` using remote chains.
- [ ] Run load tests.
- [ ] Update documentation if needed.
- [ ] Update CHANGELOG.md.

2022-01-06 02:36 UTC, LayneHaber requested changes
Needs changelog updates.

Also, how was this tested? Only using the updated integration test I added? Can we add some unit tests for this?

2022-01-06 17:46 UTC, LayneHaber requested changes
Can't skip a unit test we just added :(

2022-01-06 17:46 UTC, LayneHaber commented on packages/sdk/test/unit/sdkBase.spec.ts
> +    it.skip("finish transfer starts polling if not polling already, and stops after", async () => {
why is this skipped if it was just added?

2022-01-06 17:46 UTC, LayneHaber commented on packages/sdk/src/subgraph/subgraph.ts
> +          }
Why do we only stop polling if there are no active transactions, wouldn't that result in some weird behavior?

2022-01-06 19:57 UTC, LayneHaber commented on packages/sdk/test/unit/sdkBase.spec.ts
> +    it.skip("finish transfer starts polling if not polling already, and stops after", async () => {
skipped because needs to be deleted. modified expectations to unskip, but may still need to be deleted

2022-01-06 20:00 UTC, LayneHaber requested changes
After a conversation with @sanchaymittal found that this feature needs a bit more TLC before releasing:

- edgecase: user prepares, polling starts, subgraph loop race or not up to date so sees no active transaction, stops polling when it shouldnt
- improvement: start polling based on chainId and block number
- improvement: make polling functional instead of object oriented (similar to the router)

we will likely have immediate UX regressions if we merge this, which is not worth the reduction in subgraph queries. leaving this out of next release and taking the time to implement correctly and completely :)

thanks @sanchaymittal for the thoughtful consideration!

2022-01-07 05:19 UTC, rhlsthrm commented
OK but unfortunately this had another fix that we do need which is where the relayer send does not work without polling because the promise is set up in the wrong place. I will pull this into another branch.

2022-02-09 08:29 UTC, sanchaymittal commented
Got alternative implementation live on main

2022-02-09 08:29 UTC, closed without merging