[sdk] Return subgraph query; tidy up method headers
connext/nxtp pull request #714
Opened 2022-01-06 22:13 UTC by jakekidd

## The Problem

- We weren't actually returning the query result in the 'generic' subgraph query before 🤦‍♂️ 

## The Solution

- Now we do

- Also did a bit of tidying up, the inconsistent fn headers were bothering me.

## Checklist

- [ ] Test manually on `test-ui` using remote chains.
- [ ] Run load tests.
- [ ] Update documentation if needed.
- [ ] Update CHANGELOG.md.

2022-01-06 23:35 UTC, LayneHaber requested changes
Changelog and tests

2022-01-07 03:41 UTC, LayneHaber approved these changes
Nice job

2022-01-07 03:41 UTC, LayneHaber commented on packages/sdk/src/sdk.ts
> -    }
who commented this out instead of just deleting it lol

2022-01-07 03:41 UTC, LayneHaber commented on packages/sdk/src/sdk.ts
> +   * Cancels the given transaction.
🏅

2022-01-07 05:15 UTC, rhlsthrm approved these changes

2022-01-07 05:15 UTC, merged