try/catch hotfix on indivdual getTransactionFor in router
connext/nxtp pull request #734
Opened 2022-01-12 08:33 UTC by base0010

## The Problem

## The Solution

## Checklist

- [ ] Test manually on `test-ui` using remote chains.
- [ ] Run load tests.
- [ ] Update documentation if needed.
- [ ] Update CHANGELOG.md.

2022-01-15 20:57 UTC, LayneHaber requested changes
Also missing corresponding unit tests

2022-01-15 20:57 UTC, LayneHaber commented on packages/router/src/adapters/subgraph/subgraph.ts
> +import { BigNumber, constants, logger } from "ethers";
Wrong logger, it should be the one from the utils package

2022-01-15 20:57 UTC, LayneHaber commented on packages/router/src/adapters/subgraph/subgraph.ts
>    }
If the problem is the sdk is not configured (see #735 ) will the added try-catch fix it?

2022-01-15 20:57 UTC, LayneHaber commented on packages/router/src/adapters/subgraph/subgraph.ts
> +    logger.debug(`Problem getting transactions on chain ${chainId}\n Error ${e} `);
should log with the `@connext/nxtp-utils` logger and but things like the `error` in the context like:
```ts
{
  error: jsonifyError(e),
}
```

2022-03-23 03:37 UTC, sanchaymittal commented
closing this pr, because of inactivity. Please reopen it if necessary.

2022-03-23 03:37 UTC, closed without merging